Typescript refactor
wwnorton/inflect pull request #6
Opened 2020-09-22 21:17 UTC by grumbaut

Refactor @inflect/core into TypeScript.

2020-09-28 17:58 UTC, sh0ji requested changes
This generally looks quite good. I primarily commented on the typing rather than any specific restructuring/refactoring, as that should be a separate conversation and PR.

The one thing that stands out to me is that we need a more strict `Action` type since it's the primitive of the entire system. You'll want to iron this out before refactoring the actions into standalone functions but I might recommend using generics. Something like this might work:

```ts
type Action<T = Element, O = Record<string, unknown>> = (dom: Document, node: T, opts: O) => void | T | Promise<T>;
```

That would allow you to declare an action like this:

```ts
export type ChangeTagOptions = { tag: HTMLElementTagNameMap };
export const changeTag: Action<HTMLElement, ChangeTagOptions> = (dom, el, { tag }) => { ... }
```

A couple things that are more strict here:

- An actual document is passed to the action as a parameter instead of using a `this` context with a JSDOM property. This is more function, feels cleaner, easier to read, and opens the possibility of the `document` implementation being created by something other than JSDOM (e.g., the browser).
- Since the node type is generic, you can be very specific with it. In the above example, I said it's `HTMLElement` instead of `Element`. You could also conceivably call an action against other types of nodes that we haven't previously supported, such as a [Text](https://developer.mozilla.org/en-US/docs/Web/API/Text) node.

2020-09-28 17:58 UTC, sh0ji commented on packages/core/src/index.ts
> +	public dom: JSDOM;
You should include JSDoc comments (`/** ... */`) for public properties to enable better intellisense. You can also omit the preceding space for class properties if you like.

2020-09-28 17:58 UTC, sh0ji commented on packages/core/src/index.ts
> +		this.dom = new JSDOM(file.toString(), {
I know we discussed this but where'd you land on how Inflect should create the DOM?

I'm still inclined to have Core consume and manipulate a `document`, and leave it to the CLI or other interfaces to actually create the DOM.

2020-09-28 17:58 UTC, sh0ji commented on packages/core/src/index.ts
> +	init(): Inflect {
The return type for all methods that `return this` should be `this`. While `this` is an instance of type `Inflect`, not `Inflect` instances are `this` instance.

2020-09-28 17:58 UTC, sh0ji commented on packages/core/src/index.ts
> +				if (results && (results as Promise<void>).then) {
Does `results && 'then' in results` work here? (see [Type guards inferred from `in` operator](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-7.html#type-guards-inferred-from-in-operator))

2020-09-28 18:17 UTC, sh0ji commented on packages/core/src/index.ts
> +	public dom: JSDOM;
You know what, you can wait to add these comments until the refactor has stabilized a bit.

2020-09-28 19:18 UTC, grumbaut commented on .eslintrc.js
> +				'import/no-cycle': [2, { maxDepth: 1 }],
I think so. This was an issue with the `Actions` class importing `Inflect`. Since we're breaking out the actions into plugins, the dependency cycle issue will be resolved. Perhaps we can remove this once we refactor the actions into separate plugins?

2020-09-28 19:41 UTC, grumbaut commented on .eslintrc.js
> +				'no-void': 'off',
We can remove this. This was due to a previous error, but I forgot to remove it.
```suggestion
```

2020-09-28 21:37 UTC, grumbaut commented on packages/core/src/index.ts
> +		this.dom = new JSDOM(file.toString(), {
I'm fine either way, I think.

2020-09-28 21:39 UTC, grumbaut commented on packages/core/src/index.ts
> +				if (results && (results as Promise<void>).then) {
It does. I tried a few iterations, but I suppose not `results && 'then' in results`. TypeScript kept throwing errors, so I settled on my initial version. I'll update.

2020-09-29 14:50 UTC, grumbaut commented
@sh0ji, I've updated this branch. There are two comments I left unresolved. Also, I left out the typing for the actions until we start breaking them out.

2020-09-29 16:28 UTC, sh0ji approved these changes
Looks good! I'll merge this and then you can start on a code refactor to pull out actions and simplify the API.

2020-09-29 16:29 UTC, merged